Update patch set 1
Patch Set 1:

breaks build on aries.

/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c: In function 'wm8994_set_cdma_voicecall_receiver':
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c:2724: error: 'incall_boost_rcv' undeclared (first use in this function)
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c:2724: error: (Each undeclared identifier is reported only once
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c:2724: error: for each function it appears in.)
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c:2742: error: 'incall_mic_gain_rcv' undeclared (first use in this function)
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c: In function 'wm8994_disable_fmradio_path':
/home/jenkins/android/workspace/android/ics/kernel/samsung/aries/sound/soc/codecs/wm8994_herring.c:3998: warning: unused variable 'wm8994'

https://github.com/CyanogenMod/android_kernel_samsung_aries/commit/40c38559ff4e4d6b755fc004973d6ab3f9763302#L1R2724

https://github.com/CyanogenMod/android_kernel_samsung_aries/commit/40c38559ff4e4d6b755fc004973d6ab3f9763302#L1R2742

Patch-set: 1